# Generated by Django 4.2.11 on 2024-07-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30, verbose_name='Способ определния поставщика')),
                ('number', models.CharField(max_length=25, verbose_name='Номер процедуры')),
                ('purchase_name', models.CharField(max_length=150, verbose_name='Предмет закупки')),
                ('customer', models.CharField(max_length=200, verbose_name='Заказчик')),
                ('price', models.CharField(max_length=150, verbose_name='Начальная цена')),
                ('start', models.DateField(verbose_name='Размещено')),
                ('update', models.DateField(verbose_name='Обновлено')),
                ('end', models.DateField(max_length=25, verbose_name='Окончание подачи заявок')),
                ('purchase_link', models.URLField(max_length=150, verbose_name='Ссылка на процедуру')),
            ],
            options={
                'verbose_name': 'Процедуру',
                'verbose_name_plural': 'Архив',
            },
        ),
        migrations.CreateModel(
            name='NewProcedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30, verbose_name='Способ определния поставщика')),
                ('number', models.CharField(max_length=25, verbose_name='Номер процедуры')),
                ('purchase_name', models.CharField(max_length=150, verbose_name='Предмет закупки')),
                ('customer', models.CharField(max_length=200, verbose_name='Заказчик')),
                ('price', models.CharField(max_length=150, verbose_name='Начальная цена')),
                ('start', models.DateField(verbose_name='Размещено')),
                ('update', models.DateField(verbose_name='Обновлено')),
                ('end', models.DateField(max_length=25, verbose_name='Окончание подачи заявок')),
                ('purchase_link', models.URLField(max_length=150, verbose_name='Ссылка на процедуру')),
            ],
            options={
                'verbose_name': 'Новую процедуру',
                'verbose_name_plural': 'Новые процедуры',
            },
        ),
    ]
