# Generated by Django 4.2.11 on 2024-07-18 11:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('at_signing', 'На подписании'), ('at_performance', 'На исполнении'), ('executed', 'Исполнен')], default='at_signing', max_length=14, verbose_name='Статус')),
                ('method', models.CharField(max_length=30, verbose_name='Способ определния поставщика')),
                ('number', models.CharField(max_length=25, verbose_name='Номер процедуры')),
                ('purchase_name', models.CharField(max_length=500, verbose_name='Предмет закупки')),
                ('customer', models.CharField(max_length=200, verbose_name='Заказчик')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена контракта')),
                ('start', models.DateField(blank=True, default=None, null=True, verbose_name='Дата подписания контракта участником')),
                ('end', models.DateField(blank=True, default=None, null=True, verbose_name='Дата заключения контракта')),
                ('purchase_link', models.URLField(max_length=300, verbose_name='Ссылка на процедуру')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ProcedureForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30, verbose_name='Способ определния поставщика')),
                ('number', models.CharField(max_length=25, verbose_name='Номер процедуры')),
                ('purchase_name', models.CharField(max_length=500, verbose_name='Предмет закупки')),
                ('customer', models.CharField(max_length=200, verbose_name='Заказчик')),
                ('price', models.CharField(max_length=150, verbose_name='Начальная цена')),
                ('start', models.DateField(verbose_name='Размещено')),
                ('update', models.DateField(verbose_name='Обновлено')),
                ('end', models.DateField(max_length=25, verbose_name='Окончание подачи заявок')),
                ('purchase_link', models.URLField(max_length=300, verbose_name='Ссылка на процедуру')),
                ('status', models.CharField(choices=[('at_work', 'В работе'), ('submitted', 'Подана'), ('withdrawn', 'Отозвана')], default='at_work', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Процедуру',
                'verbose_name_plural': 'Все Процедуры в работе',
                'db_table': 'procedures_for_user',
            },
        ),
        migrations.CreateModel(
            name='ManagerProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_procedures_app.procedureforuser', verbose_name='Закупка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Процедуру',
                'verbose_name_plural': 'Процедуры менеджеров',
                'db_table': 'managers_procedures',
            },
        ),
    ]
